### PR TITLE
added optional group name property and used it for error messages

### LINKED ISSUE #72: Improved error message for properties in groups
Currently, when using property groups, you'll get an error message like this if your code doesn't match the specified order:

> Expected "top" to come before "background"

It would be nice if the error message mentioned the fact that the property is also expected to be part of a group.

Here's an example use case...at my company we are using styled-components, so we can't use the `--fix` option. So we want to require an order for properties that only requires remembering a few rules and is also readable. This is what we want to use:

```js
'order/properties-order': [
  {
    properties: ['position', 'top', 'right', 'bottom', 'left']
  },
  // remaining properties in alphabetical order
  'align-content',
  'align-items',
  // etc...
]
```

Given these rules, if a new developer starts working on a project and puts a rule, e.g. `position` or `right` in alphabetical order instead of at the top:

```css
padding: 10px;
right: 0;
```

They'll get errors like this:
> Expected "right" to come before "padding"

It would be great if the error message wouldn't just say that `right` should go above `padding`, but that it belongs in the positioning group.

I created a fork of this repo that achieves this (note: I didn't add a Jest test for it yet):
https://github.com/mbrowne/stylelint-order/tree/group-error-message
https://github.com/mbrowne/stylelint-order/commit/6ba7e43251c55bf05776265849c8d417e232406d

It allows property groups to have an optional `name` property:

```js
'order/properties-order': [
  {
    name: 'positioning',
    properties: ['position', 'top', 'right', 'bottom', 'left']
  },
```

And if a group name is present, the error includes it, e.g.:

> Expected "right" to be grouped with other "positioning" properties and to come before "padding"

I think that would be much more helpful for developers new to our rules than the current error.

Does this sound like a good solution? Should I submit a PR? Thanks.

### PR DESCRIPTION
**Pull request by mbrowne**
Resolves #72

### CODE REVIEW

**Comment by mbrowne** [comment]
I refactored the code and added tests and documentation. I thought it would be good for the readme to include at least one example of using `groupName` so I added it to the first config example using a group, but if you think that's distracting at all you can feel free to remove it. In any case I added `groupName` to the documentation for valid group config options.

**Comment by hudochenkov** [comment]
Looks good! Thanks!

**Comment by mbrowne** [comment]
Thanks for merging. Note that I didn't bump the version number—I was leaving it up to you to decide about that. Do you expect to publish a new version of the npm package sometime soon?

**Comment by hudochenkov** [comment]
I want to include a fix for https://github.com/hudochenkov/stylelint-order/issues/74 in the next version. I'll most likely do it during this week.

**Comment by hudochenkov** [comment]
Released in `stylelint-order@2.0.0`.

**Comment by mbrowne** [comment]
Great, thank you :)

**Pull request merged**
